version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "gomod"
  directories:
  - "/"
  - "/azblob"
  - "/gcs"
  - "/s3"
  schedule:
    interval: "weekly"
  groups:
    gomod:
      patterns:
      - "*"
